import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('ar'),
    Locale('he'),
  ];

  static const Map<String, String> feedbackFormLinks = {
    'en':
        'https://docs.google.com/forms/d/e/1FAIpQLSfX1m1EoigJRXq4fVeriI-eKHjC0Oy8GploFZhlj4Ca98x3bA/viewform?usp=dialog',
    'ar':
        'https://docs.google.com/forms/d/e/1FAIpQLSdvt12zLp1rmwAXavoEz9tJJrjPL3iHZ1inscE08Suyi-gjJg/viewform?usp=dialog',
    'he':
        'https://docs.google.com/forms/d/e/1FAIpQLSckD9W_uvUE8vj1DOCripUxCMVMWD3Xsk-2GAPUf4iei4cLRg/viewform?usp=dialog',
  };

  static const String feedbackEmailAddress = 'ibrahimpilot673@gmail.com';

  static const _values = <String, Map<String, String>>{
    'en': {
      'about': 'About',
'aboutIntro': 'HourDraft helps you track and log your hours by category, stay within your weekly and daily limits, and see your progress toward your yearly goal.',
'appVersion': 'Version 1.0.0',
      'appName': 'HourDraft',
      'home': 'Home',
      'history': 'History',
      'approval': 'Approval',
      'logHours': 'Log hours',
      'editHours': 'Edit hours',
      'today': 'Today',
      'thisWeek': 'This week',
      'weeklyLimit': 'Weekly limit',
      'weeklyLimits': 'Weekly limits',
      'hoursLeft': '{hours}h left',
      'indoor': 'Indoor',
      'outdoor': 'Outdoor',
      'group': 'Group',
      'category': 'Category',
      'hours': 'Hours',
      'note': 'Note',
      'optionalNote': 'Optional note',
      'date': 'Date',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'addHours': 'Add hours',
      'recentLogs': 'Recent logs',
      'noEntries': 'No hours logged yet',
      'startLogging': 'Tap + to record your first hours.',
      'total': 'Total',
      'approved': 'Approved',
      'pending': 'Pending',
      'notApproved': 'Not approved',
      'approvalStatus': 'Approval status',
      'approvalQuestion': 'Are these hours approved?',
      'approvalHint': 'You can change this later while editing the entry.',
      'yesApproved': 'Yes, approved',
      'notYet': 'Not yet',
      'approvalTitle': 'Approval tracker',
      'approvalEmpty': 'No group hours to review.',
      'approvalEmptyHint': 'Group entries will appear here with their approval status.',
      'historyTitle': 'Hour history',
      'historyEmpty': 'Your history is empty.',
      'historyEmptyHint': 'Logged hours will be saved on this device.',
      'profile': 'Profile & account',
      'analytics': 'Detailed analytics',
      'settings': 'Settings',
      'language': 'Language',
      'settingsTitle': 'Settings',
      'saveSettings': 'Save settings',
      'settingsDescription': 'Set your weekly limits, daily limits, and preferences.',
      'privacy': 'Privacy policy',
      'feedback': 'Feedback & support',
      'logOut': 'Log out',
      'name': 'Name',
      'saveProfile': 'Save changes',
      'applyLimits': 'Save settings',
      'limitDescription': 'Set weekly and daily limits for each category.',
      'languageEnglish': 'English',
      'languageArabic': 'العربية',
      'languageHebrew': 'עברית',
      'chooseLanguage': 'Choose your language',
      'deleteQuestion': 'Delete this entry?',
      'deleteHint': 'This action cannot be undone.',
      'invalidHours': 'Enter a number between 0.5 and 24.',
      'hoursLogged': '{hours}h logged',
      'daysLogged': '{days} days logged',
      'monthJanuary': 'January',
      'monthFebruary': 'February',
      'monthMarch': 'March',
      'monthApril': 'April',
      'monthMay': 'May',
      'monthJune': 'June',
      'monthJuly': 'July',
      'monthAugust': 'August',
      'monthSeptember': 'September',
      'monthOctober': 'October',
      'monthNovember': 'November',
      'monthDecember': 'December',
      'sun': 'Sun',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'noNote': 'No note',
      'entrySaved': 'Hours saved',
      'entryDeleted': 'Entry deleted',
      'unavailablePeriods': "Dates you can't volunteer",
      'unavailablePeriodsHint':
          "Add date ranges you know you'll be unavailable. They'll be shaded on the calendar and you won't be able to log hours on them.",
      'addPeriod': 'Add period',
      'periodLabel': 'What is this for?',
      'periodLabelHint': 'e.g. Exam week, Family trip',
      'startDate': 'Start date',
      'endDate': 'End date',
      'invalidPeriod': 'The start date must be before the end date.',
      'removePeriod': 'Remove',
      'noPeriods': 'No unavailable periods set.',
      'recurringDayQuestion': 'Is there a day of the week you can never volunteer, every month?',
      'recurringDayHint': 'This will repeat automatically on every matching date.',
      'yes': 'Yes',
      'no': 'No',
      'pickDay': 'Pick a day',
      'dateBlockedTitle': 'This date is unavailable',
      'dateBlockedMessage': "You marked this date as a time you can't volunteer, so you can't log hours on it.",
      'ok': 'OK',
      'yearlyGoal': 'Yearly goal',
      'yearlyGoalHint': "Total hours you're aiming for this year, across all categories.",
      'yearlyProgress': 'Yearly progress',
      'categoryShare': 'Share by category',
      'weeklyBreakdown': 'Weekly breakdown',
      'viewWeeklyBreakdown': 'View weekly breakdown',
      'appearance': 'Appearance',
      'themeSystem': 'Match device',
      'themeLight': 'Light',
      'themeDark': 'Dark',
      'sendEmail': 'Send email',
      'openForm': 'Open feedback form',
      'feedbackIntro': 'Have a bug report, idea, or question? Fill out the short form below, or email us directly.',
      'getStarted': 'Get started',
      'next': 'Next',
      'continueLabel': 'Continue',
      'dailyLimit': 'Daily limit',
      'dailyLimitHint': 'Maximum hours allowed per day for this category.',
      'showSuggestion': 'Show a time suggestion',
      'chooseYear': 'Choose year',
      'chooseYearHint': 'e.g. 2025-2026',
      'year1': 'Year 1',
      'year2': 'Year 2',
      'year3': 'Year 3',
      'exceedsWeeklyLimit': 'This will exceed your weekly {category} limit by {hours}h.',
      'exceedsDailyLimit': 'This will exceed your daily {category} limit by {hours}h.',
      'limitWarningTitle': 'Limit warning',
      'continueAnyway': 'Continue anyway',
      'hoursMustBeHalf': 'Use half-hour steps (0.5, 1, 1.5…).',
      'suggestedTime': 'Suggested: {start}:00 – {end}:00',
      'suggestionHint': 'Based on your other entries for this day.',
      'advancedSettings': 'Advanced settings',
    },
    'ar': {
      'appName': 'HourDraft',
      'about': 'حول التطبيق',
'aboutIntro': 'يساعدك HourDraft على تتبع وتسجيل ساعاتك حسب الفئة، والبقاء ضمن حدودك الأسبوعية واليومية، ومتابعة تقدمك نحو هدفك السنوي.',
'appVersion': 'الإصدار 1.0.0',
      'home': 'الرئيسية',
      'history': 'السجل',
      'approval': 'الموافقة',
      'logHours': 'تسجيل الساعات',
      'editHours': 'تعديل الساعات',
      'today': 'اليوم',
      'thisWeek': 'هذا الأسبوع',
      'weeklyLimit': 'الحد الأسبوعي',
      'weeklyLimits': 'الحدود الأسبوعية',
      'hoursLeft': 'متبقي {hours} س',
      'indoor': 'داخلي',
      'outdoor': 'خارجي',
      'group': 'جماعي',
      'category': 'الفئة',
      'hours': 'الساعات',
      'note': 'ملاحظة',
      'optionalNote': 'ملاحظة اختيارية',
      'date': 'التاريخ',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'addHours': 'إضافة ساعات',
      'recentLogs': 'آخر السجلات',
      'noEntries': 'لا توجد ساعات مسجلة',
      'startLogging': 'اضغط + لتسجيل ساعاتك الأولى.',
      'total': 'الإجمالي',
      'approved': 'تمت الموافقة',
      'pending': 'قيد الانتظار',
      'notApproved': 'لم تتم الموافقة',
      'approvalStatus': 'حالة الموافقة',
      'approvalQuestion': 'هل تمت الموافقة على هذه الساعات؟',
      'approvalHint': 'يمكنك تغيير ذلك لاحقاً أثناء تعديل السجل.',
      'yesApproved': 'نعم، تمت الموافقة',
      'notYet': 'ليس بعد',
      'approvalTitle': 'متابعة الموافقات',
      'approvalEmpty': 'لا توجد ساعات جماعية للمراجعة.',
      'approvalEmptyHint': 'ستظهر هنا السجلات الجماعية مع حالة الموافقة.',
      'historyTitle': 'سجل الساعات',
      'historyEmpty': 'السجل فارغ.',
      'historyEmptyHint': 'سيتم حفظ الساعات على هذا الجهاز.',
      'profile': 'الملف والحساب',
      'analytics': 'التحليلات التفصيلية',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'settingsTitle': 'الإعدادات',
      'saveSettings': 'حفظ الإعدادات',
      'settingsDescription': 'حدد حدودك الأسبوعية واليومية وتفضيلاتك.',
      'privacy': 'سياسة الخصوصية',
      'feedback': 'الدعم والملاحظات',
      'logOut': 'تسجيل الخروج',
      'name': 'الاسم',
      'saveProfile': 'حفظ التغييرات',
      'applyLimits': 'حفظ الإعدادات',
      'limitDescription': 'حدد الحدود الأسبوعية واليومية لكل فئة.',
      'languageEnglish': 'English',
      'languageArabic': 'العربية',
      'languageHebrew': 'עברית',
      'chooseLanguage': 'اختر لغتك',
      'deleteQuestion': 'حذف هذا السجل؟',
      'deleteHint': 'لا يمكن التراجع عن هذا الإجراء.',
      'invalidHours': 'أدخل رقماً بين ٠.٥ و٢٤.',
      'hoursLogged': 'تم تسجيل {hours} س',
      'daysLogged': 'تم التسجيل في {days} أيام',
      'monthJanuary': 'يناير',
      'monthFebruary': 'فبراير',
      'monthMarch': 'مارس',
      'monthApril': 'أبريل',
      'monthMay': 'مايو',
      'monthJune': 'يونيو',
      'monthJuly': 'يوليو',
      'monthAugust': 'أغسطس',
      'monthSeptember': 'سبتمبر',
      'monthOctober': 'أكتوبر',
      'monthNovember': 'نوفمبر',
      'monthDecember': 'ديسمبر',
      'sun': 'الأحد',
      'mon': 'الاثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'noNote': 'بدون ملاحظة',
      'entrySaved': 'تم حفظ الساعات',
      'entryDeleted': 'تم حذف السجل',
      'unavailablePeriods': 'تواريخ لا يمكنك التطوع فيها',
      'unavailablePeriodsHint': 'أضف فترات تعرف أنك ستكون غير متاح فيها. ستظهر مظللة في التقويم ولن تتمكن من تسجيل ساعات فيها.',
      'addPeriod': 'إضافة فترة',
      'periodLabel': 'ما سبب هذه الفترة؟',
      'periodLabelHint': 'مثال: أسبوع الامتحانات، رحلة عائلية',
      'startDate': 'تاريخ البدء',
      'endDate': 'تاريخ الانتهاء',
      'invalidPeriod': 'يجب أن يكون تاريخ البدء قبل تاريخ الانتهاء.',
      'removePeriod': 'إزالة',
      'noPeriods': 'لا توجد فترات غير متاحة.',
      'recurringDayQuestion': 'هل هناك يوم في الأسبوع لا يمكنك التطوع فيه أبداً، كل شهر؟',
      'recurringDayHint': 'سيتكرر هذا تلقائياً في كل تاريخ مطابق.',
      'yes': 'نعم',
      'no': 'لا',
      'pickDay': 'اختر يوماً',
      'dateBlockedTitle': 'هذا التاريخ غير متاح',
      'dateBlockedMessage': 'لقد حددت هذا التاريخ كوقت لا يمكنك التطوع فيه، لذا لا يمكنك تسجيل ساعات فيه.',
      'ok': 'حسناً',
      'yearlyGoal': 'الهدف السنوي',
      'yearlyGoalHint': 'إجمالي الساعات التي تسعى لتحقيقها هذا العام، عبر جميع الفئات.',
      'yearlyProgress': 'التقدم السنوي',
      'categoryShare': 'التوزيع حسب الفئة',
      'weeklyBreakdown': 'التوزيع الأسبوعي',
      'viewWeeklyBreakdown': 'عرض التوزيع الأسبوعي',
      'appearance': 'المظهر',
      'themeSystem': 'حسب الجهاز',
      'themeLight': 'فاتح',
      'themeDark': 'داكن',
      'sendEmail': 'إرسال بريد إلكتروني',
      'openForm': 'فتح نموذج الملاحظات',
      'feedbackIntro': 'لديك بلاغ عن خطأ، فكرة، أو سؤال؟ املأ النموذج القصير أدناه، أو راسلنا مباشرة.',
      'getStarted': 'ابدأ الآن',
      'next': 'التالي',
      'continueLabel': 'متابعة',
      'dailyLimit': 'الحد اليومي',
      'dailyLimitHint': 'الحد الأقصى للساعات المسموح بها يومياً لهذه الفئة.',
      'showSuggestion': 'إظهار اقتراح للوقت',
      'chooseYear': 'اختر السنة',
      'chooseYearHint': 'مثال: ٢٠٢٥-٢٠٢٦',
      'year1': 'السنة الأولى',
      'year2': 'السنة الثانية',
      'year3': 'السنة الثالثة',
      'exceedsWeeklyLimit': 'سيؤدي ذلك لتجاوز حدك الأسبوعي لـ {category} بمقدار {hours} س.',
      'exceedsDailyLimit': 'سيؤدي ذلك لتجاوز حدك اليومي لـ {category} بمقدار {hours} س.',
      'limitWarningTitle': 'تنبيه الحد',
      'continueAnyway': 'المتابعة على أي حال',
      'hoursMustBeHalf': 'استخدم مضاعفات نصف ساعة (٠.٥، ١، ١.٥…).',
      'suggestedTime': 'مقترح: {start}:00 – {end}:00',
      'suggestionHint': 'بناءً على باقي سجلاتك لهذا اليوم.',
      'advancedSettings': 'إعدادات متقدمة',
    },
    'he': {
      'appName': 'HourDraft',
      'about': 'אודות',
'aboutIntro': 'HourDraft עוזר לך לעקוב ולתעד את השעות שלך לפי קטגוריה, להישאר בגבולות השבועיים והיומיים שלך, ולעקוב אחר ההתקדמות שלך לעבר היעד השנתי.',
'appVersion': 'גרסה 1.0.0',
      'home': 'בית',
      'history': 'היסטוריה',
      'approval': 'אישורים',
      'logHours': 'רישום שעות',
      'editHours': 'עריכת שעות',
      'today': 'היום',
      'thisWeek': 'השבוע',
      'weeklyLimit': 'מגבלה שבועית',
      'weeklyLimits': 'מגבלות שבועיות',
      'hoursLeft': 'נשארו {hours} שעות',
      'indoor': 'בפנים',
      'outdoor': 'בחוץ',
      'group': 'קבוצתי',
      'category': 'קטגוריה',
      'hours': 'שעות',
      'note': 'הערה',
      'optionalNote': 'הערה אופציונלית',
      'date': 'תאריך',
      'save': 'שמירה',
      'cancel': 'ביטול',
      'delete': 'מחיקה',
      'addHours': 'הוספת שעות',
      'recentLogs': 'רישומים אחרונים',
      'noEntries': 'עדיין לא נרשמו שעות',
      'startLogging': 'לחצו על + כדי לרשום את השעות הראשונות.',
      'total': 'סה״כ',
      'approved': 'מאושר',
      'pending': 'ממתין',
      'notApproved': 'לא מאושר',
      'approvalStatus': 'מצב אישור',
      'approvalQuestion': 'האם השעות האלה מאושרות?',
      'approvalHint': 'אפשר לשנות זאת מאוחר יותר בעריכת הרישום.',
      'yesApproved': 'כן, מאושר',
      'notYet': 'עדיין לא',
      'approvalTitle': 'מעקב אישורים',
      'approvalEmpty': 'אין שעות קבוצתיות לבדיקה.',
      'approvalEmptyHint': 'רישומים קבוצתיים יופיעו כאן עם מצב האישור שלהם.',
      'historyTitle': 'היסטוריית שעות',
      'historyEmpty': 'ההיסטוריה ריקה.',
      'historyEmptyHint': 'השעות יישמרו במכשיר הזה.',
      'profile': 'פרופיל וחשבון',
      'analytics': 'ניתוח מפורט',
      'settings': 'הגדרות',
      'language': 'שפה',
      'settingsTitle': 'הגדרות',
      'saveSettings': 'שמירת הגדרות',
      'settingsDescription': 'הגדירו מגבלות שבועיות ויומיות והעדפות.',
      'privacy': 'מדיניות פרטיות',
      'feedback': 'משוב ותמיכה',
      'logOut': 'יציאה',
      'name': 'שם',
      'saveProfile': 'שמירת שינויים',
      'applyLimits': 'שמירת הגדרות',
      'limitDescription': 'הגדירו מגבלות שבועיות ויומיות לכל קטגוריה.',
      'languageEnglish': 'English',
      'languageArabic': 'العربية',
      'languageHebrew': 'עברית',
      'chooseLanguage': 'בחר/י שפה',
      'deleteQuestion': 'למחוק את הרישום?',
      'deleteHint': 'אי אפשר לבטל את הפעולה הזו.',
      'invalidHours': 'הזינו מספר בין 0.5 ל-24.',
      'hoursLogged': 'נרשמו {hours} שעות',
      'daysLogged': 'נרשמו {days} ימים',
      'monthJanuary': 'ינואר',
      'monthFebruary': 'פברואר',
      'monthMarch': 'מרץ',
      'monthApril': 'אפריל',
      'monthMay': 'מאי',
      'monthJune': 'יוני',
      'monthJuly': 'יולי',
      'monthAugust': 'אוגוסט',
      'monthSeptember': 'ספטמבר',
      'monthOctober': 'אוקטובר',
      'monthNovember': 'נובמבר',
      'monthDecember': 'דצמבר',
      'sun': 'א\'',
      'mon': 'ב\'',
      'tue': 'ג\'',
      'wed': 'ד\'',
      'thu': 'ה\'',
      'fri': 'ו\'',
      'sat': 'ש\'',
      'noNote': 'אין הערה',
      'entrySaved': 'השעות נשמרו',
      'entryDeleted': 'הרישום נמחק',
      'unavailablePeriods': 'תאריכים שבהם לא ניתן להתנדב',
      'unavailablePeriodsHint': 'הוסיפו טווחי תאריכים שבהם אתם יודעים שלא תהיו זמינים. הם יסומנו ביומן ולא תוכלו לרשום שעות בהם.',
      'addPeriod': 'הוספת תקופה',
      'periodLabel': 'למה מיועדת התקופה הזו?',
      'periodLabelHint': 'לדוגמה: שבוע מבחנים, טיול משפחתי',
      'startDate': 'תאריך התחלה',
      'endDate': 'תאריך סיום',
      'invalidPeriod': 'תאריך ההתחלה חייב להיות לפני תאריך הסיום.',
      'removePeriod': 'הסרה',
      'noPeriods': 'לא הוגדרו תקופות חסימה.',
      'recurringDayQuestion': 'יש יום בשבוע שבו לעולם לא תוכלו להתנדב, בכל חודש?',
      'recurringDayHint': 'זה יחזור אוטומטית בכל תאריך מתאים.',
      'yes': 'כן',
      'no': 'לא',
      'pickDay': 'בחרו יום',
      'dateBlockedTitle': 'התאריך הזה לא זמין',
      'dateBlockedMessage': 'סימנתם את התאריך הזה כזמן שבו אינכם יכולים להתנדב, לכן אי אפשר לרשום בו שעות.',
      'ok': 'אישור',
      'yearlyGoal': 'יעד שנתי',
      'yearlyGoalHint': 'סך השעות שאתם שואפים אליהן השנה, בכל הקטגוריות.',
      'yearlyProgress': 'התקדמות שנתית',
      'categoryShare': 'חלוקה לפי קטגוריה',
      'weeklyBreakdown': 'פירוט שבועי',
      'viewWeeklyBreakdown': 'הצגת פירוט שבועי',
      'appearance': 'מראה',
      'themeSystem': 'לפי המכשיר',
      'themeLight': 'בהיר',
      'themeDark': 'כהה',
      'sendEmail': 'שליחת אימייל',
      'openForm': 'פתיחת טופס משוב',
      'feedbackIntro': 'יש לכם דיווח על תקלה, רעיון או שאלה? מלאו את הטופס הקצר למטה, או כתבו לנו ישירות.',
      'getStarted': 'בואו נתחיל',
      'next': 'הבא',
      'continueLabel': 'המשך',
      'dailyLimit': 'מגבלה יומית',
      'dailyLimitHint': 'מספר השעות המקסימלי המותר ליום בקטגוריה זו.',
      'showSuggestion': 'הצגת הצעת זמן',
      'chooseYear': 'בחרו שנה',
      'chooseYearHint': 'למשל: 2025-2026',
      'year1': 'שנה 1',
      'year2': 'שנה 2',
      'year3': 'שנה 3',
      'exceedsWeeklyLimit': 'פעולה זו תחרוג ממגבלת {category} השבועית ב־{hours} שעות.',
      'exceedsDailyLimit': 'פעולה זו תחרוג ממגבלת {category} היומית ב־{hours} שעות.',
      'limitWarningTitle': 'אזהרת מגבלה',
      'continueAnyway': 'להמשיך בכל זאת',
      'hoursMustBeHalf': 'בקפיצות של חצי שעה (0.5, 1, 1.5…).',
      'suggestedTime': 'מוצע: {start}:00 – {end}:00',
      'suggestionHint': 'מבוסס על שאר הרישומים שלך ליום זה.',
      'advancedSettings': 'הגדרות מתקדמות',
    },
  };

  String tr(String key, [Map<String, String> values = const {}]) {
    var result = _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;
    for (final entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value);
    }
    return result;
  }

  String category(String value) => tr(value);

  String month(int month) => tr(const [
        '',
        'monthJanuary',
        'monthFebruary',
        'monthMarch',
        'monthApril',
        'monthMay',
        'monthJune',
        'monthJuly',
        'monthAugust',
        'monthSeptember',
        'monthOctober',
        'monthNovember',
        'monthDecember',
      ][month]);

  List<String> get weekdays => [
        tr('sun'),
        tr('mon'),
        tr('tue'),
        tr('wed'),
        tr('thu'),
        tr('fri'),
        tr('sat'),
      ];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any(
        (supported) => supported.languageCode == locale.languageCode,
      );

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}